/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/roomC.glb --types --output src/Room3D.tsx 
*/

import * as THREE from 'three'
import React, { LegacyRef, useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, MeshTransmissionMaterial, SpotLight, useDepthBuffer } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion as motion3d } from "framer-motion-3d"
import { useAtom } from 'jotai'
import { landingHeaders, loc, productViewer } from './ts/atoms'
import { motion, useAnimation } from 'framer-motion'
import { useThree } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    _ncl1_50: THREE.Mesh
    _ncl1_50_1: THREE.Mesh
    cis_inf_countdooku_cape: THREE.Mesh
    Cube002: THREE.SkinnedMesh
    Cube002_1: THREE.SkinnedMesh
    Cube020_1: THREE.Mesh
    Cube020_2: THREE.Mesh
    Cube021_1: THREE.Mesh
    Cube021_2: THREE.Mesh
    Cube022_1: THREE.Mesh
    Cube022_2: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube025_1: THREE.Mesh
    Cube025_2: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube066_1: THREE.Mesh
    Cube066_2: THREE.Mesh
    Cube067_1: THREE.Mesh
    Cube067_2: THREE.Mesh
    Cube067_3: THREE.Mesh
    Cube068_1: THREE.Mesh
    Cube068_2: THREE.Mesh
    Cube068_3: THREE.Mesh
    Cube069_1: THREE.Mesh
    Cube069_2: THREE.Mesh
    Cube069_3: THREE.Mesh
    Cube070_1: THREE.Mesh
    Cube070_2: THREE.Mesh
    Cube070_3: THREE.Mesh
    Cube071_1: THREE.Mesh
    Cube071_2: THREE.Mesh
    Cube071_3: THREE.Mesh
    Cube073_1: THREE.Mesh
    Cube073_2: THREE.Mesh
    Cube073_3: THREE.Mesh
    Cube074_1: THREE.Mesh
    Cube074_2: THREE.Mesh
    Cube074_3: THREE.Mesh
    Cube052: THREE.Mesh
    Cube052_1: THREE.Mesh
    Cube064: THREE.Mesh
    Cube064_1: THREE.Mesh
    Cube075: THREE.Mesh
    Cube075_1: THREE.Mesh
    Cube075_2: THREE.Mesh
    Cube077_1: THREE.Mesh
    Cube077_2: THREE.Mesh
    Cube077_3: THREE.Mesh
    Cube066: THREE.Mesh
    Cube078: THREE.Mesh
    Cube078_1: THREE.Mesh
    Cube079: THREE.Mesh
    Cube079_1: THREE.Mesh
    Cube080: THREE.Mesh
    Cube080_1: THREE.Mesh
    Cube081: THREE.Mesh
    Cube081_1: THREE.Mesh
    Cube071: THREE.Mesh
    Cube072: THREE.Mesh
    Cube085: THREE.Mesh
    Cube085_1: THREE.Mesh
    Cube085_2: THREE.Mesh
    Cube087: THREE.Mesh
    Cube087_1: THREE.Mesh
    Cube087_2: THREE.Mesh
    Cube089: THREE.Mesh
    Cube089_1: THREE.Mesh
    Cube089_2: THREE.Mesh
    Cube090: THREE.Mesh
    Cube090_1: THREE.Mesh
    Cube090_2: THREE.Mesh
    Cylinder017_1: THREE.Mesh
    Cylinder017_2: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder026: THREE.Mesh
    Cylinder027: THREE.Mesh
    Cylinder032: THREE.Mesh
    Cylinder032_1: THREE.Mesh
    Cylinder032_2: THREE.Mesh
    Cylinder032_3: THREE.Mesh
    Cylinder032_4: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere006: THREE.Mesh
    Plane001: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube001_3: THREE.Mesh
    Circle: THREE.Mesh
    Circle002: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
    Bone: THREE.Bone
  }
  materials: {
    Material30: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    cardboard: THREE.MeshStandardMaterial
    tape: THREE.MeshStandardMaterial
    ['Black flower pot.001']: THREE.MeshStandardMaterial
    ['metal.004']: THREE.MeshStandardMaterial
    ['cardboard.001']: THREE.MeshStandardMaterial
    ['tape.001']: THREE.MeshStandardMaterial
    keyboard: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
    ['fridge.001']: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    ['flask philodendron.002']: THREE.MeshStandardMaterial
    dumbbell: THREE.MeshStandardMaterial
    ['clock.001']: THREE.MeshStandardMaterial
    chair: THREE.MeshStandardMaterial
    ['Areca palm2.002']: THREE.MeshStandardMaterial
    ['paper.001']: THREE.MeshStandardMaterial
    ['chair.001']: THREE.MeshStandardMaterial
    ['Black flower pot.002']: THREE.MeshStandardMaterial
    paper_box: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    couch2: THREE.MeshStandardMaterial
    ['keyboard.001']: THREE.MeshStandardMaterial
    ['wall.001']: THREE.MeshStandardMaterial
    ['screen_plastic.001']: THREE.MeshStandardMaterial
    ['keys.001']: THREE.MeshStandardMaterial
    screen_off: THREE.MeshStandardMaterial
    schnee: THREE.MeshStandardMaterial
    rock: THREE.MeshStandardMaterial
    ['wall.002']: THREE.MeshStandardMaterial
    concrete: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Cube.019' | 'Cube.020' | 'Cube.021' | 'Cube.022' | 'Cube.023' | 'Cube.024' | 'Cube.025' | 'Cube.026' | 'Cube.039' | 'Cube.040' | 'Cube.041' | 'Cube.042' | 'Cube.043' | 'Cube.044' | 'Cube.045' | 'Cube.046' | 'Cube.047' | 'Cube.048' | 'Cube.049' | 'Cube.050' | 'Cube.061' | 'Cube.062' | 'Cube.065' | 'Cube.066' | 'Cube.067' | 'Cube.068' | 'Cube.069' | 'Cube.070' | 'Cube.071' | 'Cube.072' | 'Cube.073' | 'Cube.074' | 'Cube.076' | 'Cube.077' | 'Cylinder.017' | 'Cylinder.018' | 'Cylinder.026' | 'Cylinder.027' | 'Cylinder.028' | 'Icosphere' | 'Icosphere.001' | 'Icosphere.002' | 'Icosphere.003' | 'Icosphere.004' | 'Icosphere.005' | 'Icosphere.006' | 'Plane.001' | 'DummyRoot|Take 001|Base Layer' | 'cis_inf_countdooku' | 'cis_inf_countdooku_cape' | 'Cube.001' | 'Cube' | 'Circle' | 'Circle.002' | 'Cylinder' | 'Cylinder.001' | 'ArmatureAction' | 'Icosphere.008' | 'Icosphere.010' | 'Plane' | 'Plane.002' | 'Plane.003' | 'Plane.004'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>



export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/roomC.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  const [index, setIndex] = useState(0);
  const { viewport } = useThree()
  const light: any = useRef();
  const depthBuffer = useDepthBuffer({ frames: 1 })
  const [header1, setHeader1] = useAtom(landingHeaders);
  const controls = useAnimation()
  const [disposed, setDisposed] = useState(false)
  const [inPage, setInPage] = useState(false)
  const [pvAtom, setPVAtom] = useAtom(productViewer);
  const [app, setApp] = useAtom(loc);
  const [pos, setPos] = useState<any>([]);
  const [scl, setScale] = useState<any>([]);

  const rotations: any = {
    "Zur Not:": Math.PI / 2,
    "Bei uns?": Math.PI,
    "In jedem Fall:": Math.PI * 1.5,
    "Lager' alles.": 0,
  }



  //uef
  useEffect(() => {
    setIndex((index) => (index + Math.PI / 2) % (Math.PI * 2));
  }, [header1]);

  useEffect(() => {
    light.current.target.position.set([0, 1, 0.2])
  }, []);



  useEffect(() => {
    if (app === "landing") {
      setTimeout(() => {
        setDisposed(false);
        setInPage(true);
      }, 500)
    } else {
      setTimeout(() => {
        controls.start("exit").then(() => { setDisposed(true), setInPage(false) })
      }, 100)
    }
  }, [app]);


  useEffect(() => {
    const scale: any = [
      (pvAtom?.width / window.innerWidth) * viewport?.width,
      (pvAtom?.height / window.innerHeight) * viewport?.height,
      1,
    ];
    const position: any = [
      ((pvAtom?.width / window.innerWidth) * viewport.width) / 2 -
      viewport.width / 2 +
      (pvAtom?.left / window.innerWidth) * viewport.width,
      -2 -
      ((pvAtom?.height / window.innerHeight) * viewport.height) / 2 +
      viewport.height / 2 -
      (pvAtom?.top / window.innerHeight) * viewport.height,
      0,
    ];
    setPos(position);
    setScale(scale);
  }, [pvAtom]);


  const roomVariants = {
    initial: { y: -4, x: 50 },
    enter: {
      x: pos[0] + Math.max(0, Math.min(viewport.width / 12, 2.75)),
      y: pos[1],
      z: 0,
      scale: Math.max(0.5, Math.min(viewport.width / 12, 1.375)),
      rotateX: 0.2,
      rotateY: rotations[`${header1}`] + 0.5
    },
    exit: { x: 30, y: pos[1], z: 0, scale: 0 },

  }

  useEffect(() => {
    app !== "landing" && inPage === true ? controls.start("exit") : app === "landing" && inPage === true ?
      controls.start("enter") : controls.start("exit");
  }, [pos, app, index, inPage]);

  return (
    <motion3d.group transition={{
      type: "spring", damping: 10, stiffness: 50, restDelta: 0.1
    }} visible={!disposed} initial="initial" variants={roomVariants} animate={controls} scale={1.5} dispose={null}>
      <group name="Scene">
        <group name="DummyRoot" position={[0, 1, 0.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
          <SpotLight depthBuffer={depthBuffer} castShadow color={"blue"} position={[3, 6, 3]} ref={light} penumbra={1} distance={6} angle={0.35} attenuation={5} anglePower={4} intensity={2} />
          <group name="cis_inf_countdooku" position={[55.832, 52.146, -16.923]} scale={32.86}>
            <mesh name="_ncl1_50" geometry={nodes._ncl1_50.geometry} material={materials.Material30} />
            <mesh name="_ncl1_50_1" geometry={nodes._ncl1_50_1.geometry} material={materials['Material.004']} />
          </group>
          <mesh name="cis_inf_countdooku_cape" geometry={nodes.cis_inf_countdooku_cape.geometry} material={materials['Material.002']} position={[55.832, 52.146, -16.923]} scale={32.86} />
        </group>
        <group name="Armature" position={[1.742, 3.299, -1.246]} rotation={[0, 0.909, 0]} scale={0.341}>
          <primitive object={nodes.Bone} />
          <group name="monster">
            <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.003']} skeleton={nodes.Cube002.skeleton} />
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.005']} skeleton={nodes.Cube002_1.skeleton} />
          </group>
        </group>
        <group name="Icosphere008" position={[0.89, 3.014, -15.39]} rotation={[0, 0, 0.363]} scale={[0.115, 0.175, 0.115]} />
        <group name="Icosphere010" position={[0.89, 3.014, -15.792]} rotation={[0, 0, 0.363]} scale={[0.115, 0.175, 0.115]} />
        <group name="Cube019" position={[0.58, 0.671, -0.534]} scale={5.351}>
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.cardboard} />
          <mesh name="Cube020_2" geometry={nodes.Cube020_2.geometry} material={materials.tape} />
        </group>
        <group name="Cube020" position={[0.726, 0.671, -0.707]} scale={5.351}>
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.cardboard} />
          <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials.tape} />
        </group>
        <group name="Cube021" position={[0.58, 0.671, -0.534]} scale={5.351}>
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.cardboard} />
          <mesh name="Cube022_2" geometry={nodes.Cube022_2.geometry} material={materials.tape} />
        </group>
        <group name="Cube022" position={[0.58, 0.671, -0.534]} scale={5.351}>
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.cardboard} />
          <mesh name="Cube023_2" geometry={nodes.Cube023_2.geometry} material={materials.tape} />
        </group>
        <group name="Cube023" position={[-0.333, 0.671, -1.013]} scale={5.351}>
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials.cardboard} />
          <mesh name="Cube024_2" geometry={nodes.Cube024_2.geometry} material={materials.tape} />
        </group>
        <group name="Cube024" position={[0.58, 0.671, -0.534]} scale={5.351}>
          <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials.cardboard} />
          <mesh name="Cube025_2" geometry={nodes.Cube025_2.geometry} material={materials.tape} />
        </group>
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Black flower pot.001']} position={[-0.015, 0.635, 0.077]} scale={5.351} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Black flower pot.001']} position={[-0.015, 0.635, 0.077]} scale={5.351} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['metal.004']} position={[-2.306, 2.066, -0.781]} scale={[2.034, 0.047, 0.542]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['metal.004']} position={[-2.292, 2.066, -3.301]} scale={[2.034, 0.047, 0.542]} />
        <group name="Cube041" position={[-2.963, 2.774, -0.797]} rotation={[0, -0.98, 0]} scale={5.351}>
          <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['cardboard.001']} />
          <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials['tape.001']} />
        </group>
        <group name="Cube042" position={[-1.52, 1.453, -0.797]} rotation={[0, -0.622, 0]} scale={3.951}>
          <mesh name="Cube066_1" geometry={nodes.Cube066_1.geometry} material={materials['cardboard.001']} />
          <mesh name="Cube066_2" geometry={nodes.Cube066_2.geometry} material={materials['tape.001']} />
        </group>
        <group name="Cube043" position={[-2.801, 3.964, -3.338]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube067_1" geometry={nodes.Cube067_1.geometry} material={materials.keyboard} />
          <mesh name="Cube067_2" geometry={nodes.Cube067_2.geometry} material={materials.paper} />
          <mesh name="Cube067_3" geometry={nodes.Cube067_3.geometry} material={materials['fridge.001']} />
        </group>
        <group name="Cube044" position={[-3.092, 3.964, -3.338]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube068_1" geometry={nodes.Cube068_1.geometry} material={materials.keyboard} />
          <mesh name="Cube068_2" geometry={nodes.Cube068_2.geometry} material={materials.paper} />
          <mesh name="Cube068_3" geometry={nodes.Cube068_3.geometry} material={materials.chrome} />
        </group>
        <group name="Cube045" position={[-3.398, 3.964, -3.338]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube069_1" geometry={nodes.Cube069_1.geometry} material={materials.keyboard} />
          <mesh name="Cube069_2" geometry={nodes.Cube069_2.geometry} material={materials.paper} />
          <mesh name="Cube069_3" geometry={nodes.Cube069_3.geometry} material={materials['flask philodendron.002']} />
        </group>
        <group name="Cube046" position={[-2.079, 3.964, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials.keyboard} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials.paper} />
          <mesh name="Cube070_3" geometry={nodes.Cube070_3.geometry} material={materials.chrome} />
        </group>
        <group name="Cube047" position={[-2.369, 3.964, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube071_1" geometry={nodes.Cube071_1.geometry} material={materials.keyboard} />
          <mesh name="Cube071_2" geometry={nodes.Cube071_2.geometry} material={materials.paper} />
          <mesh name="Cube071_3" geometry={nodes.Cube071_3.geometry} material={materials.dumbbell} />
        </group>
        <group name="Cube048" position={[-2.675, 3.964, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube073_1" geometry={nodes.Cube073_1.geometry} material={materials.keyboard} />
          <mesh name="Cube073_2" geometry={nodes.Cube073_2.geometry} material={materials.paper} />
          <mesh name="Cube073_3" geometry={nodes.Cube073_3.geometry} material={materials.chrome} />
        </group>
        <group name="Cube049" position={[-2.963, 3.964, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube074_1" geometry={nodes.Cube074_1.geometry} material={materials.keyboard} />
          <mesh name="Cube074_2" geometry={nodes.Cube074_2.geometry} material={materials.paper} />
          <mesh name="Cube074_3" geometry={nodes.Cube074_3.geometry} material={materials['clock.001']} />
        </group>
        <group name="Cube050" position={[-0.894, 2.814, -3.305]} rotation={[0, -0.552, 0]} scale={5.351}>
          <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['cardboard.001']} />
          <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials['tape.001']} />
        </group>
        <group name="Cube061" position={[-1.063, 4.073, -0.797]} rotation={[0, -0.98, 0]} scale={5.351}>
          <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['cardboard.001']} />
          <mesh name="Cube064_1" geometry={nodes.Cube064_1.geometry} material={materials['tape.001']} />
        </group>
        <group name="Cube062" position={[-1.468, 2.676, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={materials.keyboard} />
          <mesh name="Cube075_1" geometry={nodes.Cube075_1.geometry} material={materials.paper} />
          <mesh name="Cube075_2" geometry={nodes.Cube075_2.geometry} material={materials.chrome} />
        </group>
        <group name="Cube065" position={[-1.774, 2.676, -0.82]} scale={[0.132, 0.417, 0.38]}>
          <mesh name="Cube077_1" geometry={nodes.Cube077_1.geometry} material={materials.keyboard} />
          <mesh name="Cube077_2" geometry={nodes.Cube077_2.geometry} material={materials.paper} />
          <mesh name="Cube077_3" geometry={nodes.Cube077_3.geometry} material={materials.chair} />
        </group>
        <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={materials.cardboard} position={[-1.181, 1.582, 0.84]} rotation={[-Math.PI / 2, 0.397, Math.PI / 2]} scale={[0.029, 0.016, 0.816]} />
        <group name="Cube067" position={[-1.785, 2.328, -3.38]} scale={[0.354, 0.354, 0.45]}>
          <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials['Areca palm2.002']} />
          <mesh name="Cube078_1" geometry={nodes.Cube078_1.geometry} material={materials['paper.001']} />
        </group>
        <group name="Cube068" position={[-2.619, 2.328, -3.38]} scale={[0.354, 0.354, 0.45]}>
          <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={materials['chair.001']} />
          <mesh name="Cube079_1" geometry={nodes.Cube079_1.geometry} material={materials['paper.001']} />
        </group>
        <group name="Cube069" position={[-3.455, 2.328, -3.38]} scale={[0.354, 0.354, 0.45]}>
          <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={materials['clock.001']} />
          <mesh name="Cube080_1" geometry={nodes.Cube080_1.geometry} material={materials['paper.001']} />
        </group>
        <group name="Cube070" position={[-3.455, 2.478, -3.38]} scale={[0.354, 0.354, 0.45]}>
          <mesh name="Cube081" geometry={nodes.Cube081.geometry} material={materials['Black flower pot.002']} />
          <mesh name="Cube081_1" geometry={nodes.Cube081_1.geometry} material={materials['paper.001']} />
        </group>
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials.paper_box} position={[-0.894, 1.511, -3.305]} rotation={[0, -0.731, 0]} scale={4.467} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[-0.727, 1.366, -3.619]} rotation={[0, 0.087, -Math.PI]} scale={[-0.126, -0.187, -0.002]} />
        <group name="Cube073" position={[-4.116, 2.587, 0.455]} rotation={[-1.697, 1.571, 0]} scale={[-2.197, -2.197, -0.06]}>
          <mesh name="Cube085" geometry={nodes.Cube085.geometry} material={materials.keyboard} />
          <mesh name="Cube085_1" geometry={nodes.Cube085_1.geometry} material={materials['clock.001']} />
          <mesh name="Cube085_2" geometry={nodes.Cube085_2.geometry} material={materials['Material.007']} />
        </group>
        <group name="Cube074" position={[-4.537, 2.587, 0.455]} rotation={[-1.697, 1.571, 0]} scale={[-2.197, -2.197, -0.06]}>
          <mesh name="Cube087" geometry={nodes.Cube087.geometry} material={materials.keyboard} />
          <mesh name="Cube087_1" geometry={nodes.Cube087_1.geometry} material={materials['clock.001']} />
          <mesh name="Cube087_2" geometry={nodes.Cube087_2.geometry} material={materials['Material.007']} />
        </group>
        <group name="Cube076" position={[-3.083, 2.136, 0.373]} rotation={[-1.697, 1.571, 0]} scale={[-1.719, -1.719, -0.047]}>
          <mesh name="Cube089" geometry={nodes.Cube089.geometry} material={materials.keyboard} />
          <mesh name="Cube089_1" geometry={nodes.Cube089_1.geometry} material={materials['chair.001']} />
          <mesh name="Cube089_2" geometry={nodes.Cube089_2.geometry} material={materials['Material.007']} />
        </group>
        <group name="Cube077" position={[-3.411, 2.136, 0.373]} rotation={[-1.697, 1.571, 0]} scale={[-1.719, -1.719, -0.047]}>
          <mesh name="Cube090" geometry={nodes.Cube090.geometry} material={materials.keyboard} />
          <mesh name="Cube090_1" geometry={nodes.Cube090_1.geometry} material={materials.chair} />
          <mesh name="Cube090_2" geometry={nodes.Cube090_2.geometry} material={materials['Material.007']} />
        </group>
        <group name="Cylinder017" position={[-2.903, 4.173, 2.916]} rotation={[-0.213, 0.091, 0.166]} scale={0.39}>
          <mesh name="Cylinder017_1" geometry={nodes.Cylinder017_1.geometry} material={materials.couch2} />
          <mesh name="Cylinder017_2" geometry={nodes.Cylinder017_2.geometry} material={materials['keyboard.001']} />
        </group>
        <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials['clock.001']} position={[-2.745, 3.491, 3.597]} rotation={[1.16, 0.014, -0.162]} scale={0.075} />
        <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials.dumbbell} position={[-3.794, 1.138, -0.85]} rotation={[0, 0.863, 0]} scale={5.351} />
        <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials.dumbbell} position={[-3.519, 1.138, -0.86]} rotation={[0, 0.863, 0]} scale={5.351} />
        <group name="Cylinder028" position={[-2.652, -0.393, -3.33]} rotation={[Math.PI, -1.456, Math.PI]} scale={2.785}>
          <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials['wall.001']} />
          <mesh name="Cylinder032_1" geometry={nodes.Cylinder032_1.geometry} material={materials['screen_plastic.001']} />
          <mesh name="Cylinder032_2" geometry={nodes.Cylinder032_2.geometry} material={materials['keys.001']} />
          <mesh name="Cylinder032_3" geometry={nodes.Cylinder032_3.geometry} material={materials['keyboard.001']} />
          <mesh name="Cylinder032_4" geometry={nodes.Cylinder032_4.geometry} material={materials.screen_off} />
        </group>
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['keyboard.001']} position={[-2.883, 3.608, 3.489]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials['keyboard.001']} position={[-2.617, 3.616, 3.439]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials['keyboard.001']} position={[-2.883, 3.315, 3.544]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials['keyboard.001']} position={[-2.617, 3.323, 3.494]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere004" geometry={nodes.Icosphere004.geometry} material={materials['keyboard.001']} position={[-2.735, 3.271, 3.544]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={materials['keyboard.001']} position={[-2.981, 3.385, 3.516]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={materials['keyboard.001']} position={[-2.518, 3.374, 3.444]} rotation={[0, 0.05, 0]} scale={0.061} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.schnee} position={[-2.806, 0.945, 3.042]} scale={1.492} />
        <group name="Cube001" position={[-0.726, 0.671, -0.524]} rotation={[0, -0.746, 0]} scale={5.351}>
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.cardboard} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.tape} />
        </group>
        <group name="Cube" position={[0, 0.316, 0]} scale={[5.4, 0.312, 5.4]}>
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.rock} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials['wall.002']} />
          <mesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials.concrete} />
        </group>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.011']} position={[2.903, 0.597, 2.838]} scale={1.724} />
        <mesh geometry={nodes.Circle002.geometry} position={[2.903, 0.597, 2.838]} scale={1.724} >
          <MeshTransmissionMaterial samples={8} resolution={512} thickness={0.3} roughness={0.2} anisotropy={1} chromaticAberration={0.2} />

        </mesh>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Black flower pot.002']} position={[1.159, 0.987, 4.594]} rotation={[Math.PI, -0.788, Math.PI / 2]} scale={[0.151, 0.996, 0.151]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Black flower pot.002']} position={[4.429, 6.861, 1.122]} rotation={[2.179, 0.542, -2.381]} scale={[0.151, 0.996, 0.151]} />
        <group name="Plane" position={[2.83, 0.627, -2.83]} scale={2.569}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.010']} />
        </group>
        <group name="Plane002" position={[-2.83, 0.627, -2.83]} scale={2.569}>
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.009']} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['Material.010']} />
        </group>
        <group name="Plane003" position={[2.83, 0.627, 2.83]} scale={2.569}>
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.009']} />
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['Material.010']} />
        </group>
        <group name="Plane004" position={[-2.83, 0.627, 2.83]} scale={2.569}>
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.009']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.010']} />
        </group>
      </group>
    </motion3d.group>

  )
}

useGLTF.preload('/roomC.glb')

